Avoid using wildcard in verb
IBM/ibm-namespace-scope-operator pull request #78
Opened 2021-03-10 04:16 UTC by horis233

2021-03-11 09:13 UTC, pgodowski requested changes

2021-03-11 09:13 UTC, pgodowski commented on README.md
> +      - escalate
let's put on hold this change till we clarify it does not effectively increase the privileged access

2021-03-31 18:04 UTC, horis233 commented
@bitscuit @Daniel-Fan Could you help review this PR?

2021-03-31 18:11 UTC, Daniel-Fan approved these changes
/lgtm

2021-03-31 18:15 UTC, merged